name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Debug Environment
      run: |
        echo "Java version:"
        java -version
        echo "Android SDK location:"
        echo $ANDROID_HOME
        echo "Gradle version:"
        ./gradlew --version

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Verify APK exists
      run: |
        echo "Checking for APK files:"
        find . -name "*.apk" -type f
        echo "Contents of app/build/outputs/apk/debug/:"
        ls -la app/build/outputs/apk/debug/ || echo "Directory does not exist"

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: pilltracker-debug-apk
        path: app-debug.apk
        retention-days: 30
      working-directory: app/build/outputs/apk/debug