name: Firebase App Distribution

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses | cat

      - name: Build Debug APK
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Find APK path
        id: find_apk
        shell: bash
        run: |
          APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "No APK found" >&2
            exit 1
          fi
          echo "apk=$APK_PATH" >> $GITHUB_OUTPUT
          echo "Found APK at $APK_PATH"

      - name: Create google-services.json
        if: success()
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Debug Firebase Configuration
        if: success()
        run: |
          echo "Firebase App ID: ${{ secrets.FIREBASE_APP_ID }}"
          echo "Firebase Token exists: ${{ secrets.FIREBASE_TOKEN != '' }}"
          echo "Google Services JSON exists: ${{ secrets.GOOGLE_SERVICES_JSON != '' }}"

      - name: Distribute to Firebase App Distribution
        if: success()
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          file: ${{ steps.find_apk.outputs.apk }}
          releaseNotes: |
            🚀 New build from commit ${{ github.sha }}
            📅 Built on: ${{ github.event.head_commit.timestamp }}
            👤 Author: ${{ github.event.head_commit.author.name }}
            
            Changes:
            - Latest updates from main branch
            - Bug fixes and improvements