name: Step by Step Debug

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout
      run: echo "✅ Step 1: Checkout successful"
      
    - name: Step 2 - Checkout code
      uses: actions/checkout@v4
      
    - name: Step 3 - After checkout
      run: echo "✅ Step 3: After checkout successful"
      
    - name: Step 4 - Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Step 5 - After JDK setup
      run: |
        echo "✅ Step 5: JDK setup successful"
        java -version
        
    - name: Step 6 - Setup Android SDK
      uses: android-actions/setup-android@v3.2.2
      with:
        api-level: 34
        build-tools: 34.0.0
        
    - name: Step 7 - After Android SDK setup
      run: |
        echo "✅ Step 7: Android SDK setup successful"
        echo "ANDROID_HOME: $ANDROID_HOME"
        ls -la $ANDROID_HOME || echo "ANDROID_HOME not found"
        
    - name: Step 8 - Accept licenses
      run: |
        echo "Step 8: Accepting Android SDK licenses..."
        yes | sdkmanager --licenses || echo "License acceptance failed"
        echo "✅ Step 8: License acceptance completed"
        
    - name: Step 9 - Check gradlew
      run: |
        echo "Step 9: Checking gradlew..."
        ls -la gradlew || echo "gradlew not found"
        chmod +x gradlew
        echo "✅ Step 9: gradlew ready"
        
    - name: Step 10 - Test gradlew
      run: |
        echo "Step 10: Testing gradlew..."
        ./gradlew --version || echo "gradlew failed"
        echo "✅ Step 10: gradlew test completed"
        
    - name: Step 11 - Try build
      run: |
        echo "Step 11: Attempting build..."
        ./gradlew assembleDebug --no-daemon --stacktrace || echo "Build failed"
        echo "✅ Step 11: Build attempt completed"
        
    - name: Step 12 - Check results
      run: |
        echo "Step 12: Checking build results..."
        find . -name "*.apk" -type f || echo "No APK files found"
        ls -la app/build/outputs/apk/debug/ || echo "APK directory not found"
        echo "✅ Step 12: Results check completed"