name: Working Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.2
      with:
        api-level: 34
        build-tools: 34.0.0
        ndk-version: latest

    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses || true
        sdkmanager --update || true

    - name: Set up environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

    - name: Debug environment
      run: |
        echo "=== Environment Debug ==="
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "JAVA_HOME: $JAVA_HOME"
        echo "PATH: $PATH"
        echo "Java version:"
        java -version
        echo "Android SDK contents:"
        ls -la $ANDROID_HOME || echo "ANDROID_HOME not found"
        echo "Gradle wrapper:"
        ls -la gradlew || echo "gradlew not found"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test Gradle wrapper
      run: ./gradlew --version

    - name: Clean project
      run: ./gradlew clean

    - name: Build Debug APK
      run: |
        ./gradlew assembleDebug \
          --no-daemon \
          --stacktrace \
          --info \
          --warning-mode all

    - name: Verify APK exists
      run: |
        echo "=== APK Verification ==="
        find . -name "*.apk" -type f
        echo "APK directory contents:"
        ls -la app/build/outputs/apk/debug/ || echo "APK directory not found"
        echo "APK file details:"
        ls -la app/build/outputs/apk/debug/app-debug.apk || echo "APK file not found"

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: working-android-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30